/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thecodebook;

/**
 *
 * @author Kwanrudee
 */
public class appOffline extends javax.swing.JFrame {

    // String st23 = "/images/st25.png";
    /**
     * Creates new form appOffline
     */
    public appOffline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        java1 = new javax.swing.JLabel();
        java2 = new javax.swing.JLabel();
        java3 = new javax.swing.JLabel();
        java4 = new javax.swing.JLabel();
        java5 = new javax.swing.JLabel();
        searchJava = new javax.swing.JTextField();
        btnSJava = new javax.swing.JButton();
        scrool = new javax.swing.JScrollPane();
        showCode = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        csh1 = new javax.swing.JLabel();
        csh2 = new javax.swing.JLabel();
        csh3 = new javax.swing.JLabel();
        csh4 = new javax.swing.JLabel();
        csh5 = new javax.swing.JLabel();
        searchCshap = new javax.swing.JTextField();
        btnSCShap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        searchPython = new javax.swing.JTextField();
        btnSPython = new javax.swing.JButton();
        pyt1 = new javax.swing.JLabel();
        pyt2 = new javax.swing.JLabel();
        pyt3 = new javax.swing.JLabel();
        pyt4 = new javax.swing.JLabel();
        pyt5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        searchVB = new javax.swing.JTextField();
        btnSVB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        vb1 = new javax.swing.JLabel();
        vb2 = new javax.swing.JLabel();
        vb3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        site = new javax.swing.JComboBox<>();
        searchStEx = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showCodeSite = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        searchCodeUser = new javax.swing.JTextField();
        btnSearchCodeUser = new javax.swing.JButton();
        resultTitle1 = new javax.swing.JLabel();
        userName1 = new javax.swing.JLabel();
        resultTitle2 = new javax.swing.JLabel();
        userName2 = new javax.swing.JLabel();
        rating2 = new javax.swing.JLabel();
        rating1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        showResult = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Code Book");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        java1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                java1MouseEntered(evt);
            }
        });

        java2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java2MouseClicked(evt);
            }
        });

        java3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java3MouseClicked(evt);
            }
        });

        java4.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        java5.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        searchJava.setFont(new java.awt.Font("Aharoni", 1, 16)); // NOI18N
        searchJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJavaActionPerformed(evt);
            }
        });

        btnSJava.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSJava.setText("Search");
        btnSJava.setActionCommand("");
        btnSJava.setMaximumSize(new java.awt.Dimension(119, 27));
        btnSJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSJavaActionPerformed(evt);
            }
        });

        showCode.setBackground(new java.awt.Color(204, 204, 204));
        showCode.setColumns(20);
        showCode.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        showCode.setRows(5);
        scrool.setViewportView(showCode);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchJava, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSJava, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(java1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchJava, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSJava, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(java1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(java2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(java3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(java4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(java5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addComponent(scrool))
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Java  ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        csh1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh2.setBackground(new java.awt.Color(255, 255, 255));
        csh2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh4.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh5.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        searchCshap.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        btnSCShap.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSCShap.setText("   Search   ");

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(csh4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(csh3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(csh2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(csh5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(csh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(searchCshap, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSCShap)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSCShap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCshap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(csh1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("    C#    ", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        searchPython.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        btnSPython.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSPython.setText("   Search   ");

        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pyt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(searchPython, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSPython))
                    .addComponent(pyt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(searchPython, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSPython))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pyt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(pyt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Python ", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btnSVB.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSVB.setText("   Search   ");

        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(searchVB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSVB)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(searchVB))
                    .addComponent(btnSVB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(vb1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(vb2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(vb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   VB   ", jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sexc.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel13.setText("Question : ");

        jLabel14.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel14.setText("Site :");

        site.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        site.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stack Overflow", "Web Applications", "Game Development", "Programmers", "Web Master" }));

        searchStEx.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        searchStEx.setText("Search");
        searchStEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStExActionPerformed(evt);
            }
        });

        showCodeSite.setColumns(20);
        showCodeSite.setRows(5);
        jScrollPane1.setViewportView(showCodeSite);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(searchStEx)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStEx))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Stake Exchang  ", jPanel2);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 255));
        jLabel19.setText("The Code Book");

        jLabel20.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel20.setText("Title : ");

        btnSearchCodeUser.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSearchCodeUser.setText("Search");
        btnSearchCodeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeUserActionPerformed(evt);
            }
        });

        resultTitle1.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        resultTitle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTitle1MouseClicked(evt);
            }
        });

        userName1.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        resultTitle2.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        userName2.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        showResult.setColumns(20);
        showResult.setRows(5);
        jScrollPane5.setViewportView(showResult);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(userName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rating2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(rating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(searchCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchCodeUser))
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(346, 346, 346))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchCodeUser)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rating1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rating2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Share Code  ", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("  Update  ", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJavaActionPerformed

    }//GEN-LAST:event_searchJavaActionPerformed

    private void btnSJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSJavaActionPerformed
        java1.setText(" Java Code Samples  Google Developers " + searchJava.getText());
        java2.setText(searchJava.getText() + "  Defining Data Classes with JDO");
        java3.setText(searchJava.getText() + "  Java - Date & Time ");
        java4.setText(" simple " + searchJava.getText());
        java5.setText(" JDBC - Sample, Example Code " + searchJava.getText());


    }//GEN-LAST:event_btnSJavaActionPerformed

    private void java1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java1MouseClicked
        showCode.setText(java1.getText()
                + "\n"
                + "___________________________________________________________________________________________________________________________"
                + "\n"
                + "\n"
                + "\n"
                + "package com.google.api.services.samples.youtube.cmdline.data;\n"
                + "\n"
                + "import com.google.api.client.auth.oauth2.Credential;\n"
                + "import com.google.api.client.googleapis.json.GoogleJsonResponseException;\n"
                + "import com.google.api.services.samples.youtube.cmdline.Auth;\n"
                + "import com.google.api.services.youtube.YouTube;\n"
                + "import com.google.api.services.youtube.model.*;\n"
                + "import com.google.common.collect.Lists;\n"
                + "\n"
                + "import java.util.Calendar;\n"
                + "import java.util.List;"
                + "private static YouTube youtube;\n"
                + "\n"
                + "    \n"
                + "    private static String VIDEO_ID = \"L-oNKK1CrnU\";\n"
                + "\n"
                + "\n"
                + "    \n"
                + "    public static void main(String[] args) {\n"
                + "\n"
                + "        \n"
                + "        List<String> scopes = Lists.newArrayList(\"https://www.googleapis.com/auth/youtube\");\n"
                + "\n"
                + "        try {\n"
                + "            \n"
                + "            Credential credential = Auth.authorize(scopes, \"channelbulletin\");\n"
                + "\n"
                + "            \n"
                + "            youtube = new YouTube.Builder(Auth.HTTP_TRANSPORT, Auth.JSON_FACTORY, credential).setApplicationName(\n"
                + "                    \"youtube-cmdline-channelbulletin-sample\").build();\n"
                + "\n"
                + "            \n"
                + "            YouTube.Channels.List channelRequest = youtube.channels().list(\"contentDetails\");\n"
                + "            channelRequest.setMine(true);\n"
                + "\n"
                + "            \n"
                + "            channelRequest.setFields(\"items/contentDetails\");\n"
                + "            ChannelListResponse channelResult = channelRequest.execute();\n"
                + "\n"
                + "            List<Channel> channelsList = channelResult.getItems();\n"
                + "\n"
                + "            if (channelsList != null) {\n"
                + "                \n"
                + "                String channelId = channelsList.get(0).getId();\n"
                + "\n"
                + "                \n"
                + "                ActivitySnippet snippet = new ActivitySnippet();\n"
                + "                snippet.setChannelId(channelId);\n"
                + "                Calendar cal = Calendar.getInstance();\n"
                + "                snippet.setDescription(\"Bulletin test video via YouTube API on \" + cal.getTime());\n"
                + "\n"
                + "                \n"
                + "                ResourceId resource = new ResourceId();\n"
                + "                resource.setKind(\"youtube#video\");\n"
                + "                resource.setVideoId(VIDEO_ID);\n"
                + "\n"
                + "                ActivityContentDetailsBulletin bulletin = new ActivityContentDetailsBulletin();\n"
                + "                bulletin.setResourceId(resource);\n"
                + "\n"
                + "                \n"
                + "                ActivityContentDetails contentDetails = new ActivityContentDetails();\n"
                + "                contentDetails.setBulletin(bulletin);\n"
                + "\n"
                + "                \n"
                + "                Activity activity = new Activity();\n"
                + "                activity.setSnippet(snippet);\n"
                + "                activity.setContentDetails(contentDetails);\n"
                + "\n"
                + "           \n"
                + "                YouTube.Activities.Insert insertActivities =\n"
                + "                        youtube.activities().insert(\"contentDetails,snippet\", activity);\n"
                + "                \n"
                + "                Activity newActivityInserted = insertActivities.execute();\n"
                + "\n"
                + "                if (newActivityInserted != null) {\n"
                + "                    System.out.println(\n"
                + "                            \"New Activity inserted of type \" + newActivityInserted.getSnippet().getType());\n"
                + "                    System.out.println(\" - Video id \"\n"
                + "                            + newActivityInserted.getContentDetails().getBulletin().getResourceId().getVideoId());\n"
                + "                    System.out.println(\n"
                + "                            \" - Description: \" + newActivityInserted.getSnippet().getDescription());\n"
                + "                    System.out.println(\" - Posted on \" + newActivityInserted.getSnippet().getPublishedAt());\n"
                + "                } else {\n"
                + "                    System.out.println(\"Activity failed.\");\n"
                + "                }\n"
                + "\n"
                + "            } else {\n"
                + "                System.out.println(\"No channels are assigned to this user.\");\n"
                + "            }\n"
                + "        } catch (GoogleJsonResponseException e) {\n"
                + "            e.printStackTrace();\n"
                + "            System.err.println(\"There was a service error: \" + e.getDetails().getCode() + \" : \"\n"
                + "                    + e.getDetails().getMessage());\n"
                + "\n"
                + "        } catch (Throwable t) {\n"
                + "            t.printStackTrace();\n"
                + "        }\n"
                + "    }\n"
                + "}");


    }//GEN-LAST:event_java1MouseClicked

    private void java1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_java1MouseEntered

    private void java2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java2MouseClicked
        showCode.setText(java2.getText() + "   Java");
    }//GEN-LAST:event_java2MouseClicked

    private void java3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java3MouseClicked
        showCode.setText(java3.getText() + "   Java");
    }//GEN-LAST:event_java3MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        csh1.setText("Load Data Source Dataflow Sample Code (C#) " + searchJava.getText());
        csh2.setText(searchJava.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " + searchJava.getText());
        csh4.setText("C# SQL Server Connection " + searchJava.getText());
        csh5.setText(searchJava.getText() + " C# SQL Server Connection ");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        csh1.setText("Load Data Source Dataflow Sample Code (C#) " + searchJava.getText());
        csh2.setText(searchJava.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " + searchJava.getText());
        csh4.setText("C# SQL Server Connection " + searchJava.getText());
        csh5.setText(searchJava.getText() + " C# SQL Server Connection ");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        java1.setText("Java Code Samples  Google Developers " + searchJava.getText());
        java2.setText(searchJava.getText() + "  Defining Data Classes with JDO");
        java3.setText(searchJava.getText() + "  Java - Date & Time ");
        java4.setText("simple " + searchJava.getText());
        java5.setText("JDBC - Sample, Example Code " + searchJava.getText());

    }//GEN-LAST:event_jPanel3MouseClicked
//String st23 = "/images/st25.png";
    private void btnSearchCodeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeUserActionPerformed
        resultTitle1.setText(searchCodeUser.getText() + " Examples");
        resultTitle2.setText("2D " + searchCodeUser.getText() + " Examples");

        userName1.setText("by.Eiji");
        userName2.setText("by.Kwang");

        //  String st23 = "/images/st25.png";
        //  rating1.setText(st25);

    }//GEN-LAST:event_btnSearchCodeUserActionPerformed

    private void resultTitle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTitle1MouseClicked
        showResult.setText(resultTitle1.getText()
                + "\n"
                + "___________________________________________________________________________________________________________________________"
                + "\n"
                + "\n"
                + "\n"
                + " class ArrayDemo {\n"
                + "    public static void main(String[] args) {\n"
                + "        // declares an array of integers\n"
                + "        int[] anArray;\n"
                + "\n"
                + "        // allocates memory for 10 integers\n"
                + "        anArray = new int[10];\n"
                + "           \n"
                + "        // initialize first element\n"
                + "        anArray[0] = 100;\n"
                + "        // initialize second element\n"
                + "        anArray[1] = 200;\n"
                + "        // and so forth\n"
                + "        anArray[2] = 300;\n"
                + "        anArray[3] = 400;\n"
                + "        anArray[4] = 500;\n"
                + "        anArray[5] = 600;\n"
                + "        anArray[6] = 700;\n"
                + "        anArray[7] = 800;\n"
                + "        anArray[8] = 900;\n"
                + "        anArray[9] = 1000;\n"
                + "\n"
                + "        System.out.println(\"Element at index 0: \"\n"
                + "                           + anArray[0]);\n"
                + "        System.out.println(\"Element at index 1: \"\n"
                + "                           + anArray[1]);\n"
                + "        System.out.println(\"Element at index 2: \"\n"
                + "                           + anArray[2]);\n"
                + "        System.out.println(\"Element at index 3: \"\n"
                + "                           + anArray[3]);\n"
                + "        System.out.println(\"Element at index 4: \"\n"
                + "                           + anArray[4]);\n"
                + "        System.out.println(\"Element at index 5: \"\n"
                + "                           + anArray[5]);\n"
                + "        System.out.println(\"Element at index 6: \"\n"
                + "                           + anArray[6]);\n"
                + "        System.out.println(\"Element at index 7: \"\n"
                + "                           + anArray[7]);\n"
                + "        System.out.println(\"Element at index 8: \"\n"
                + "                           + anArray[8]);\n"
                + "        System.out.println(\"Element at index 9: \"\n"
                + "                           + anArray[9]);\n"
                + "    }\n"
                + "} ");


    }//GEN-LAST:event_resultTitle1MouseClicked

    private void searchStExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStExActionPerformed

        showCodeSite.setText(question.getText() + "  ----> Stack Overflow : "
                + "\n"
                + "___________________________________________________________________________________________________________________________"
                + "\n"
                + "\n"
                + "\n"
                
                + "import java.sql.*;\n"
                + "\n"
                + "public class JDBCExample {\n"
                + "\n"
                + "   static final String JDBC_DRIVER = \"com.mysql.jdbc.Driver\";  \n"
                + "   static final String DB_URL = \"jdbc:mysql://localhost/\";\n"
                + "\n"
                + "\n"
                + "   static final String USER = \"username\";\n"
                + "   static final String PASS = \"password\";\n"
                + "   \n"
                + "   public static void main(String[] args) {\n"
                + "   Connection conn = null;\n"
                + "   Statement stmt = null;\n"
                + "   try{\n"
                + "\n"
                + "      Class.forName(\"com.mysql.jdbc.Driver\");\n"
                + "\n"
                + "\n"
                + "      System.out.println(\"Connecting to database...\");\n"
                + "      conn = DriverManager.getConnection(DB_URL, USER, PASS);\n"
                + "\n"
                
                + "      System.out.println(\"Creating database...\");\n"
                + "      stmt = conn.createStatement();\n"
                + "      \n"
                + "      String sql = \"CREATE DATABASE STUDENTS\";\n"
                + "      stmt.executeUpdate(sql);\n"
                + "      System.out.println(\"Database created successfully...\");\n"
                + "   }catch(SQLException se){\n"
                + "\n"
                + "      se.printStackTrace();\n"
                + "   }catch(Exception e){\n"
                + "\n"
                + "      e.printStackTrace();\n"
                + "   }finally{\n"
                + "\n"
                + "      try{\n"
                + "         if(stmt!=null)\n"
                + "            stmt.close();\n"
                + "      }catch(SQLException se2){\n"
                + " }\n"
                + "      try{\n"
                + "         if(conn!=null)\n"
                + "            conn.close();\n"
                + "      }catch(SQLException se){\n"
                + "         se.printStackTrace();\n"
                + "      }\n"
                + "   }\n"
                + "   System.out.println(\"Goodbye!\");\n"
                + "}\n"
                + "}"
        );


    }//GEN-LAST:event_searchStExActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appOffline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSCShap;
    private javax.swing.JButton btnSJava;
    private javax.swing.JButton btnSPython;
    private javax.swing.JButton btnSVB;
    private javax.swing.JButton btnSearchCodeUser;
    private javax.swing.JLabel csh1;
    private javax.swing.JLabel csh2;
    private javax.swing.JLabel csh3;
    private javax.swing.JLabel csh4;
    private javax.swing.JLabel csh5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel java1;
    private javax.swing.JLabel java2;
    private javax.swing.JLabel java3;
    private javax.swing.JLabel java4;
    private javax.swing.JLabel java5;
    private javax.swing.JLabel pyt1;
    private javax.swing.JLabel pyt2;
    private javax.swing.JLabel pyt3;
    private javax.swing.JLabel pyt4;
    private javax.swing.JLabel pyt5;
    private javax.swing.JTextField question;
    private javax.swing.JLabel rating1;
    private javax.swing.JLabel rating2;
    private javax.swing.JLabel resultTitle1;
    private javax.swing.JLabel resultTitle2;
    private javax.swing.JScrollPane scrool;
    private javax.swing.JTextField searchCodeUser;
    private javax.swing.JTextField searchCshap;
    private javax.swing.JTextField searchJava;
    private javax.swing.JTextField searchPython;
    private javax.swing.JButton searchStEx;
    private javax.swing.JTextField searchVB;
    private javax.swing.JTextArea showCode;
    private javax.swing.JTextArea showCodeSite;
    private javax.swing.JTextArea showResult;
    private javax.swing.JComboBox<String> site;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel vb1;
    private javax.swing.JLabel vb2;
    private javax.swing.JLabel vb3;
    // End of variables declaration//GEN-END:variables

    private void choose1MouseClicked() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
