/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thecodebook;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kwanrudee
 */
public class appOffline extends javax.swing.JFrame {

    public ArrayList<String> list = new ArrayList<String>();

    // String st23 = "/images/st25.png";
    /**
     * Creates new form appOffline
     */
    public appOffline() {
        initComponents();
        rating1.setVisible(false);
        rating2.setVisible(false);
        rating3.setVisible(false);
        rating4.setVisible(false);

        //test fuction
        /*
        list.add("database");
        list.add("array");
        list.add("Tic tat tor");
        DefaultListModel<String> model = new DefaultListModel<String>();
        for (String s : list ){
            model.addElement(s);
        }
        this.jList1.setModel(model);
         */
        //listJava
        list.add("database");
        list.add("array");
        list.add("Tic tat tor");
        list.add("Shape");
        list.add("add Audio");
        list.add("How to use jButton");
        list.add("How to use jTextField");
        list.add("How to use jPasswordField");
        list.add("How to use jTextArea");
        list.add("How to use jRadioButton");
        list.add("How to use jRadioGroup");
        list.add("How to use jCheckBox");
        list.add("How to use jCombobox");
        list.add("How to use jTable");
        list.add("How to use jSlider");
        list.add("Graphic User Interface (GUI)");
        list.add("jFileChooser");
        list.add("jMenuBar");
        list.add("XML Parsers");
        list.add("JSON");
        list.add("Print Square");
        list.add("Birthday Problem");
        list.add("Enum demo");
        list.add("Copy file");
        list.add("Collection framework");
        list.add("Fetch URL");
        DefaultListModel<String> model = new DefaultListModel<String>();
        for (String s : list) {
            model.addElement(s);
        }
        this.listJava.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabJava = new javax.swing.JPanel();
        searchJava = new javax.swing.JTextField();
        btnSJava = new javax.swing.JButton();
        scrool = new javax.swing.JScrollPane();
        showCode = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        listJava = new javax.swing.JList<>();
        copy = new javax.swing.JButton();
        tabCsh = new javax.swing.JPanel();
        csh1 = new javax.swing.JLabel();
        csh2 = new javax.swing.JLabel();
        csh3 = new javax.swing.JLabel();
        csh4 = new javax.swing.JLabel();
        csh5 = new javax.swing.JLabel();
        searchCshap = new javax.swing.JTextField();
        btnSCShap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        tabPy = new javax.swing.JPanel();
        searchPython = new javax.swing.JTextField();
        btnSPython = new javax.swing.JButton();
        pyt1 = new javax.swing.JLabel();
        pyt2 = new javax.swing.JLabel();
        pyt3 = new javax.swing.JLabel();
        pyt4 = new javax.swing.JLabel();
        pyt5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        tabVB = new javax.swing.JPanel();
        searchVB = new javax.swing.JTextField();
        btnSVB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        vb1 = new javax.swing.JLabel();
        vb2 = new javax.swing.JLabel();
        vb3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        site = new javax.swing.JComboBox<>();
        searchStEx = new javax.swing.JButton();
        showCodeSite1 = new javax.swing.JLabel();
        showCodeSite2 = new javax.swing.JLabel();
        showCodeSite3 = new javax.swing.JLabel();
        sh21 = new javax.swing.JLabel();
        sh22 = new javax.swing.JLabel();
        sh23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        searchCodeUser = new javax.swing.JTextField();
        btnSearchCodeUser = new javax.swing.JButton();
        resultTitle1 = new javax.swing.JLabel();
        userName1 = new javax.swing.JLabel();
        resultTitle2 = new javax.swing.JLabel();
        userName2 = new javax.swing.JLabel();
        rating2 = new javax.swing.JLabel();
        rating1 = new javax.swing.JLabel();
        resultTitle3 = new javax.swing.JLabel();
        resultTitle4 = new javax.swing.JLabel();
        userName3 = new javax.swing.JLabel();
        userName4 = new javax.swing.JLabel();
        rating3 = new javax.swing.JLabel();
        rating4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Code Book");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tabJava.setBackground(new java.awt.Color(255, 255, 255));
        tabJava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabJavaMouseClicked(evt);
            }
        });

        searchJava.setFont(new java.awt.Font("Aharoni", 1, 16)); // NOI18N
        searchJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJavaActionPerformed(evt);
            }
        });

        btnSJava.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSJava.setText("Search");
        btnSJava.setActionCommand("");
        btnSJava.setMaximumSize(new java.awt.Dimension(119, 27));
        btnSJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSJavaActionPerformed(evt);
            }
        });

        showCode.setBackground(new java.awt.Color(204, 204, 204));
        showCode.setColumns(20);
        showCode.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        showCode.setRows(5);
        scrool.setViewportView(showCode);

        listJava.setFont(new java.awt.Font("Aharoni", 2, 18)); // NOI18N
        listJava.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listJava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listJavaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(listJava);

        copy.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        copy.setText("Copy");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabJavaLayout = new javax.swing.GroupLayout(tabJava);
        tabJava.setLayout(tabJavaLayout);
        tabJavaLayout.setHorizontalGroup(
            tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabJavaLayout.createSequentialGroup()
                        .addComponent(searchJava, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSJava, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addGroup(tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabJavaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabJavaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copy)
                        .addContainerGap())))
        );
        tabJavaLayout.setVerticalGroup(
            tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabJavaLayout.createSequentialGroup()
                        .addGroup(tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchJava, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSJava, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabJavaLayout.createSequentialGroup()
                        .addComponent(copy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tabJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Java  ", tabJava);

        tabCsh.setBackground(new java.awt.Color(255, 255, 255));
        tabCsh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCshMouseClicked(evt);
            }
        });

        csh1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh2.setBackground(new java.awt.Color(255, 255, 255));
        csh2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh4.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh5.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        searchCshap.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        btnSCShap.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSCShap.setText("Search");

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout tabCshLayout = new javax.swing.GroupLayout(tabCsh);
        tabCsh.setLayout(tabCshLayout);
        tabCshLayout.setHorizontalGroup(
            tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCshLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(csh4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(csh3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csh2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csh5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabCshLayout.createSequentialGroup()
                        .addComponent(searchCshap, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSCShap, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );
        tabCshLayout.setVerticalGroup(
            tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCshLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCshap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSCShap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(tabCshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCshLayout.createSequentialGroup()
                        .addComponent(csh1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(csh5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("    C#    ", tabCsh);

        tabPy.setBackground(new java.awt.Color(255, 255, 255));
        tabPy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPyMouseClicked(evt);
            }
        });

        searchPython.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        btnSPython.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSPython.setText("Search");
        btnSPython.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPythonActionPerformed(evt);
            }
        });

        pyt1.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        pyt2.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        pyt3.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        pyt4.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        pyt5.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout tabPyLayout = new javax.swing.GroupLayout(tabPy);
        tabPy.setLayout(tabPyLayout);
        tabPyLayout.setHorizontalGroup(
            tabPyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pyt4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addGroup(tabPyLayout.createSequentialGroup()
                        .addComponent(searchPython, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSPython, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pyt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pyt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
        );
        tabPyLayout.setVerticalGroup(
            tabPyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPython, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSPython))
                .addGap(27, 27, 27)
                .addGroup(tabPyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPyLayout.createSequentialGroup()
                        .addComponent(pyt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(pyt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pyt5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Python ", tabPy);

        tabVB.setBackground(new java.awt.Color(255, 255, 255));

        btnSVB.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSVB.setText("Search");

        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout tabVBLayout = new javax.swing.GroupLayout(tabVB);
        tabVB.setLayout(tabVBLayout);
        tabVBLayout.setHorizontalGroup(
            tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addComponent(searchVB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSVB, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 551, Short.MAX_VALUE))
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vb3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                        .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabVBLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(tabVBLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tabVBLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(tabVBLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))))))
        );
        tabVBLayout.setVerticalGroup(
            tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVBLayout.createSequentialGroup()
                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchVB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSVB))
                        .addGap(33, 33, 33)
                        .addComponent(vb1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(vb2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(vb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGroup(tabVBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabVBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   VB   ", tabVB);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sexc.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel13.setText("Question : ");

        jLabel14.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel14.setText("Site :");

        site.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        site.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stack Overflow", "Web Applications", "Game Development", "Programmers", "Web Master" }));
        site.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteActionPerformed(evt);
            }
        });

        searchStEx.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        searchStEx.setText("Search");
        searchStEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStExActionPerformed(evt);
            }
        });

        showCodeSite1.setBackground(new java.awt.Color(0, 0, 0));
        showCodeSite1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        showCodeSite1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        showCodeSite1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCodeSite1MouseClicked(evt);
            }
        });

        showCodeSite2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        showCodeSite2.setForeground(new java.awt.Color(0, 0, 204));
        showCodeSite2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        showCodeSite3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        showCodeSite3.setForeground(new java.awt.Color(0, 102, 0));
        showCodeSite3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        sh21.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        sh22.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        sh22.setForeground(new java.awt.Color(0, 0, 204));

        sh23.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        sh23.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(searchStEx))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showCodeSite3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showCodeSite1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addComponent(showCodeSite2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sh21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sh22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sh23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStEx))
                .addGap(41, 41, 41)
                .addComponent(showCodeSite1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCodeSite2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCodeSite3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sh21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Stake Exchang  ", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 255));
        jLabel19.setText("The Code Book");

        jLabel20.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel20.setText("Title : ");

        btnSearchCodeUser.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        btnSearchCodeUser.setText("Search");
        btnSearchCodeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeUserActionPerformed(evt);
            }
        });

        resultTitle1.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        resultTitle1.setForeground(new java.awt.Color(0, 0, 153));
        resultTitle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTitle1MouseClicked(evt);
            }
        });

        userName1.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        resultTitle2.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        resultTitle2.setForeground(new java.awt.Color(0, 0, 153));

        userName2.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        rating2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/35.png"))); // NOI18N

        rating1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/45.jpg"))); // NOI18N

        resultTitle3.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        resultTitle3.setForeground(new java.awt.Color(0, 0, 153));

        resultTitle4.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        resultTitle4.setForeground(new java.awt.Color(0, 0, 153));

        userName3.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        userName4.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N

        rating3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/35.png"))); // NOI18N

        rating4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/25.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(searchCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchCodeUser))
                    .addComponent(jLabel19)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(resultTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(resultTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(resultTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(userName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rating2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rating3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rating4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(346, 346, 346))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchCodeUser)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rating1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(rating2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(userName3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rating3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(resultTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rating4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(resultTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Shared Code  ", jPanel5);

        jButton1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton1.setText(" Update ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJavaActionPerformed

    }//GEN-LAST:event_searchJavaActionPerformed

    private void btnSJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSJavaActionPerformed
        /* java1.setText(" Java Code Samples  Google Developers " + searchJava.getText());
        java2.setText(searchJava.getText() + "  Defining Data Classes with JDO");
        java3.setText(searchJava.getText() + "  Java - Date & Time ");
        java4.setText(" simple " + searchJava.getText());
        java5.setText(" JDBC - Sample, Example Code " + searchJava.getText());

         */

        DefaultListModel<String> model = new DefaultListModel<String>();
        for (Object s : list) {
            if (((String) s).contains(this.searchJava.getText().toString())) {
                model.addElement(s.toString());
            }

        }
        this.listJava.setModel(model);
    }//GEN-LAST:event_btnSJavaActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        /*
        java1.setText(" Java Code Samples  Google Developers " + searchJava.getText());
        java2.setText(searchJava.getText() + "  Defining Data Classes with JDO");
        java3.setText(searchJava.getText() + "  Java - Date & Time ");
        java4.setText(" simple " + searchJava.getText());
        java5.setText(" JDBC - Sample, Example Code " + searchJava.getText());

        csh1.setText("Load Data Source Dataflow Sample Code (C#) " + searchJava.getText());
        csh2.setText(searchJava.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " + searchJava.getText());
        csh4.setText("C# SQL Server Connection " + searchJava.getText());
        csh5.setText(searchJava.getText() + " C# SQL Server Connection ");

        pyt1.setText("Python " + searchPython.getText() + " Access - TutorialsPoint");
        pyt2.setText(searchPython.getText() + "  Basic Python / Beginner Code");
        pyt3.setText(searchPython.getText() + "  Python Programming ");
        pyt4.setText("An Introduction to " + searchPython.getText() + " with Python");
        pyt5.setText("Full Stack Python " + searchPython.getText());
         */
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void tabCshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCshMouseClicked
        /*
        csh1.setText("Load Data Source Dataflow Sample Code (C#) " + searchJava.getText());
        csh2.setText(searchJava.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " + searchJava.getText());
        csh4.setText("C# SQL Server Connection " + searchJava.getText());
        csh5.setText(searchJava.getText() + " C# SQL Server Connection ");
         */
    }//GEN-LAST:event_tabCshMouseClicked

    private void tabJavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabJavaMouseClicked
        /*      java1.setText("Java Code Samples  Google Developers " + searchJava.getText());
        java2.setText(searchJava.getText() + "  Defining Data Classes with JDO");
        java3.setText(searchJava.getText() + "  Java - Date & Time ");
        java4.setText("simple " + searchJava.getText());
        java5.setText("JDBC - Sample, Example Code " + searchJava.getText());
         */
    }//GEN-LAST:event_tabJavaMouseClicked
//String st23 = "/images/st25.png";
    private void btnSearchCodeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeUserActionPerformed
        resultTitle1.setText(searchCodeUser.getText() + " Examples");
        resultTitle2.setText("2D " + searchCodeUser.getText() + " Examples");
        resultTitle3.setText("Code easy to use " + searchCodeUser.getText() + " Examples");
        resultTitle4.setText(searchCodeUser.getText() + "Code Advance");

        userName1.setText("by.Eiji");
        userName2.setText("by.Kwang");
        userName3.setText("by.pop");
        userName4.setText("by.Kwanrudee");

        //  String st23 = "/images/st25.png";
        //  rating1.setText(st25);
        rating1.setVisible(true);
        rating2.setVisible(true);
        rating3.setVisible(true);
        rating4.setVisible(true);

    }//GEN-LAST:event_btnSearchCodeUserActionPerformed

    private void resultTitle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTitle1MouseClicked

    }//GEN-LAST:event_resultTitle1MouseClicked

    private void searchStExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStExActionPerformed

        showCodeSite1.setText(
                question.getText() + " Newest " + question.getText() + "Questions - Stack Overflow" + question.getText()
        );
        /*
        showCodeSite2.setText(
                question.getText() + "Development Stack Exchange"
                + "\n"
                + "\n");
         */
        showCodeSite2.setText(
                question.getText() + question.getText() + " An array is an ordered data structure consisting of a collection of elements ");

        /*
        showCodeSite2.setText(searchStEx.getText()
                + "An array is an ordered data structure consisting of a collection"
                + "of elements ( values or variables), each identified by one "
                + "\n"
                + "(single dimensional array or vector) or ...");
         */
        showCodeSite3.setText("stackoverflow.com/questions/tagged/arrays");

        sh21.setText("javascript - Appending to " + question.getText() + "- Stack Overflow");
        sh22.setText("How do I append to an array in JavaScript? ... Use the push() function to append to an array:");
        sh23.setText("stackoverflow.com/questions/351409/appending-to-array");

    }//GEN-LAST:event_searchStExActionPerformed

    private void tabPyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPyMouseClicked
        /*
        pyt1.setText("Python " + searchPython.getText() + " Access - TutorialsPoint");
        pyt2.setText(searchPython.getText() + "  Basic Python / Beginner Code");
        pyt3.setText(searchPython.getText() + "  Python Programming ");
        pyt4.setText("An Introduction to " + searchPython.getText() + " with Python");
        pyt5.setText("Full Stack Python " + searchPython.getText());
         */
    }//GEN-LAST:event_tabPyMouseClicked

    private void btnSPythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPythonActionPerformed
        /*
        pyt1.setText("Python " + searchPython.getText() + " Access - TutorialsPoint");
        pyt2.setText(searchPython.getText() + "  Basic Python / Beginner Code");
        pyt3.setText(searchPython.getText() + "  Python Programming ");
        pyt4.setText("An Introduction to " + searchPython.getText() + " with Python");
        pyt5.setText("Full Stack Python " + searchPython.getText());
         */
    }//GEN-LAST:event_btnSPythonActionPerformed

    private void showCodeSite1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCodeSite1MouseClicked
        //openWebsite

    }//GEN-LAST:event_showCodeSite1MouseClicked

    private void listJavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listJavaMouseClicked
        showCode.setText("class ArrayDemo {\n"
                + "    public static void main(String[] args) {\n"
                + "        // declares an array of integers\n"
                + "        int[] anArray;\n"
                + "\n"
                + "        // allocates memory for 10 integers\n"
                + "        anArray = new int[10];\n"
                + "           \n"
                + "        // initialize first element\n"
                + "        anArray[0] = 100;\n"
                + "        // initialize second element\n"
                + "        anArray[1] = 200;\n"
                + "        // and so forth\n"
                + "        anArray[2] = 300;\n"
                + "        anArray[3] = 400;\n"
                + "        anArray[4] = 500;\n"
                + "        anArray[5] = 600;\n"
                + "        anArray[6] = 700;\n"
                + "        anArray[7] = 800;\n"
                + "        anArray[8] = 900;\n"
                + "        anArray[9] = 1000;\n"
                + "\n"
                + "        System.out.println(\"Element at index 0: \"\n"
                + "                           + anArray[0]);\n"
                + "        System.out.println(\"Element at index 1: \"\n"
                + "                           + anArray[1]);\n"
                + "        System.out.println(\"Element at index 2: \"\n"
                + "                           + anArray[2]);\n"
                + "        System.out.println(\"Element at index 3: \"\n"
                + "                           + anArray[3]);\n"
                + "        System.out.println(\"Element at index 4: \"\n"
                + "                           + anArray[4]);\n"
                + "        System.out.println(\"Element at index 5: \"\n"
                + "                           + anArray[5]);\n"
                + "        System.out.println(\"Element at index 6: \"\n"
                + "                           + anArray[6]);\n"
                + "        System.out.println(\"Element at index 7: \"\n"
                + "                           + anArray[7]);\n"
                + "        System.out.println(\"Element at index 8: \"\n"
                + "                           + anArray[8]);\n"
                + "        System.out.println(\"Element at index 9: \"\n"
                + "                           + anArray[9]);\n"
                + "    }\n"
                + "} " + listJava.getSelectedValue().toString());
    }//GEN-LAST:event_listJavaMouseClicked

    private void siteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siteActionPerformed

    }//GEN-LAST:event_siteActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Do you want to update it?",
                "Update",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Update complete");
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appOffline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSCShap;
    private javax.swing.JButton btnSJava;
    private javax.swing.JButton btnSPython;
    private javax.swing.JButton btnSVB;
    private javax.swing.JButton btnSearchCodeUser;
    private javax.swing.JButton copy;
    private javax.swing.JLabel csh1;
    private javax.swing.JLabel csh2;
    private javax.swing.JLabel csh3;
    private javax.swing.JLabel csh4;
    private javax.swing.JLabel csh5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JList<String> listJava;
    private javax.swing.JLabel pyt1;
    private javax.swing.JLabel pyt2;
    private javax.swing.JLabel pyt3;
    private javax.swing.JLabel pyt4;
    private javax.swing.JLabel pyt5;
    private javax.swing.JTextField question;
    private javax.swing.JLabel rating1;
    private javax.swing.JLabel rating2;
    private javax.swing.JLabel rating3;
    private javax.swing.JLabel rating4;
    private javax.swing.JLabel resultTitle1;
    private javax.swing.JLabel resultTitle2;
    private javax.swing.JLabel resultTitle3;
    private javax.swing.JLabel resultTitle4;
    private javax.swing.JScrollPane scrool;
    private javax.swing.JTextField searchCodeUser;
    private javax.swing.JTextField searchCshap;
    private javax.swing.JTextField searchJava;
    private javax.swing.JTextField searchPython;
    private javax.swing.JButton searchStEx;
    private javax.swing.JTextField searchVB;
    private javax.swing.JLabel sh21;
    private javax.swing.JLabel sh22;
    private javax.swing.JLabel sh23;
    private javax.swing.JTextArea showCode;
    private javax.swing.JLabel showCodeSite1;
    private javax.swing.JLabel showCodeSite2;
    private javax.swing.JLabel showCodeSite3;
    private javax.swing.JComboBox<String> site;
    private javax.swing.JPanel tabCsh;
    private javax.swing.JPanel tabJava;
    private javax.swing.JPanel tabPy;
    private javax.swing.JPanel tabVB;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel userName3;
    private javax.swing.JLabel userName4;
    private javax.swing.JLabel vb1;
    private javax.swing.JLabel vb2;
    private javax.swing.JLabel vb3;
    // End of variables declaration//GEN-END:variables

    private void choose1MouseClicked() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
