/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thecodebook;

/**
 *
 * @author Kwanrudee
 */
public class appOffline extends javax.swing.JFrame {

    /**
     * Creates new form appOffline
     */
    public appOffline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        scrool = new javax.swing.JScrollPane();
        showCode = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        java1 = new javax.swing.JLabel();
        java2 = new javax.swing.JLabel();
        java3 = new javax.swing.JLabel();
        java4 = new javax.swing.JLabel();
        java5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        csh1 = new javax.swing.JLabel();
        csh2 = new javax.swing.JLabel();
        csh3 = new javax.swing.JLabel();
        csh4 = new javax.swing.JLabel();
        csh5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Code Book");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(177, 540, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        search.setFont(new java.awt.Font("Aharoni", 1, 16)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton6.setText("Search");
        jButton6.setActionCommand("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        showCode.setBackground(new java.awt.Color(153, 153, 255));
        showCode.setColumns(20);
        showCode.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        showCode.setRows(5);
        scrool.setViewportView(showCode);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        java1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                java1MouseEntered(evt);
            }
        });

        java2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java2MouseClicked(evt);
            }
        });

        java3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N
        java3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                java3MouseClicked(evt);
            }
        });

        java4.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        java5.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(java5, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(java4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(java1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(java1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(java2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(java3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(java4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(java5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Java  ", jPanel3);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        csh1.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh2.setBackground(new java.awt.Color(255, 255, 255));
        csh2.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh3.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh4.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        csh5.setFont(new java.awt.Font("Aharoni", 2, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(csh5, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(csh3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addComponent(csh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csh4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(csh1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(csh2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(csh3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(csh4)
                .addGap(18, 18, 18)
                .addComponent(csh5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    C#    ", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(" Python ", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("   VB   ", jPanel7);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       
    }//GEN-LAST:event_searchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java1.setText("Java Code Samples  Google Developers " + search.getText());
        java2.setText(search.getText() + "  Defining Data Classes with JDO");
        java3.setText(search.getText() + "  Java - Date & Time ");
        java4.setText("simple " + search.getText());
        java5.setText("JDBC - Sample, Example Code " + search.getText());


    }//GEN-LAST:event_jButton6ActionPerformed

    private void java1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java1MouseClicked
        showCode.setText(java1.getText()
                + "\n"
                + "___________________________________________________________________________________________________________________________"
                + "\n"
                + "\n"
                + "\n"
                + "package com.google.api.services.samples.youtube.cmdline.data;\n"
                + "\n"
                + "import com.google.api.client.auth.oauth2.Credential;\n"
                + "import com.google.api.client.googleapis.json.GoogleJsonResponseException;\n"
                + "import com.google.api.services.samples.youtube.cmdline.Auth;\n"
                + "import com.google.api.services.youtube.YouTube;\n"
                + "import com.google.api.services.youtube.model.*;\n"
                + "import com.google.common.collect.Lists;\n"
                + "\n"
                + "import java.util.Calendar;\n"
                + "import java.util.List;"
                + "private static YouTube youtube;\n"
                + "\n"
                + "    \n"
                + "    private static String VIDEO_ID = \"L-oNKK1CrnU\";\n"
                + "\n"
                + "\n"
                + "    \n"
                + "    public static void main(String[] args) {\n"
                + "\n"
                + "        \n"
                + "        List<String> scopes = Lists.newArrayList(\"https://www.googleapis.com/auth/youtube\");\n"
                + "\n"
                + "        try {\n"
                + "            \n"
                + "            Credential credential = Auth.authorize(scopes, \"channelbulletin\");\n"
                + "\n"
                + "            \n"
                + "            youtube = new YouTube.Builder(Auth.HTTP_TRANSPORT, Auth.JSON_FACTORY, credential).setApplicationName(\n"
                + "                    \"youtube-cmdline-channelbulletin-sample\").build();\n"
                + "\n"
                + "            \n"
                + "            YouTube.Channels.List channelRequest = youtube.channels().list(\"contentDetails\");\n"
                + "            channelRequest.setMine(true);\n"
                + "\n"
                + "            \n"
                + "            channelRequest.setFields(\"items/contentDetails\");\n"
                + "            ChannelListResponse channelResult = channelRequest.execute();\n"
                + "\n"
                + "            List<Channel> channelsList = channelResult.getItems();\n"
                + "\n"
                + "            if (channelsList != null) {\n"
                + "                \n"
                + "                String channelId = channelsList.get(0).getId();\n"
                + "\n"
                + "                \n"
                + "                ActivitySnippet snippet = new ActivitySnippet();\n"
                + "                snippet.setChannelId(channelId);\n"
                + "                Calendar cal = Calendar.getInstance();\n"
                + "                snippet.setDescription(\"Bulletin test video via YouTube API on \" + cal.getTime());\n"
                + "\n"
                + "                \n"
                + "                ResourceId resource = new ResourceId();\n"
                + "                resource.setKind(\"youtube#video\");\n"
                + "                resource.setVideoId(VIDEO_ID);\n"
                + "\n"
                + "                ActivityContentDetailsBulletin bulletin = new ActivityContentDetailsBulletin();\n"
                + "                bulletin.setResourceId(resource);\n"
                + "\n"
                + "                \n"
                + "                ActivityContentDetails contentDetails = new ActivityContentDetails();\n"
                + "                contentDetails.setBulletin(bulletin);\n"
                + "\n"
                + "                \n"
                + "                Activity activity = new Activity();\n"
                + "                activity.setSnippet(snippet);\n"
                + "                activity.setContentDetails(contentDetails);\n"
                + "\n"
                + "           \n"
                + "                YouTube.Activities.Insert insertActivities =\n"
                + "                        youtube.activities().insert(\"contentDetails,snippet\", activity);\n"
                + "                \n"
                + "                Activity newActivityInserted = insertActivities.execute();\n"
                + "\n"
                + "                if (newActivityInserted != null) {\n"
                + "                    System.out.println(\n"
                + "                            \"New Activity inserted of type \" + newActivityInserted.getSnippet().getType());\n"
                + "                    System.out.println(\" - Video id \"\n"
                + "                            + newActivityInserted.getContentDetails().getBulletin().getResourceId().getVideoId());\n"
                + "                    System.out.println(\n"
                + "                            \" - Description: \" + newActivityInserted.getSnippet().getDescription());\n"
                + "                    System.out.println(\" - Posted on \" + newActivityInserted.getSnippet().getPublishedAt());\n"
                + "                } else {\n"
                + "                    System.out.println(\"Activity failed.\");\n"
                + "                }\n"
                + "\n"
                + "            } else {\n"
                + "                System.out.println(\"No channels are assigned to this user.\");\n"
                + "            }\n"
                + "        } catch (GoogleJsonResponseException e) {\n"
                + "            e.printStackTrace();\n"
                + "            System.err.println(\"There was a service error: \" + e.getDetails().getCode() + \" : \"\n"
                + "                    + e.getDetails().getMessage());\n"
                + "\n"
                + "        } catch (Throwable t) {\n"
                + "            t.printStackTrace();\n"
                + "        }\n"
                + "    }\n"
                + "}");


    }//GEN-LAST:event_java1MouseClicked

    private void java1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_java1MouseEntered

    private void java2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java2MouseClicked
        showCode.setText(java2.getText() + "   Java");
    }//GEN-LAST:event_java2MouseClicked

    private void java3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_java3MouseClicked
        showCode.setText(java3.getText() + "   Java");
    }//GEN-LAST:event_java3MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        csh1.setText("Load Data Source Dataflow Sample Code (C#) "+search.getText());
        csh2.setText(search.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " +search.getText());
        csh4.setText("C# SQL Server Connection " + search.getText());
        csh5.setText(search.getText()+ " C# SQL Server Connection ");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        csh1.setText("Load Data Source Dataflow Sample Code (C#) "+search.getText());
        csh2.setText(search.getText() + " c# - Storing data in code");
        csh3.setText("markrendle/Simple.Data - C# " +search.getText());
        csh4.setText("C# SQL Server Connection " + search.getText());
        csh5.setText(search.getText()+ " C# SQL Server Connection ");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       java1.setText("Java Code Samples  Google Developers " + search.getText());
        java2.setText(search.getText() + "  Defining Data Classes with JDO");
        java3.setText(search.getText() + "  Java - Date & Time ");
        java4.setText("simple " + search.getText());
        java5.setText("JDBC - Sample, Example Code " + search.getText());
 
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appOffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appOffline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel csh1;
    private javax.swing.JLabel csh2;
    private javax.swing.JLabel csh3;
    private javax.swing.JLabel csh4;
    private javax.swing.JLabel csh5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel java1;
    private javax.swing.JLabel java2;
    private javax.swing.JLabel java3;
    private javax.swing.JLabel java4;
    private javax.swing.JLabel java5;
    private javax.swing.JScrollPane scrool;
    private javax.swing.JTextField search;
    private javax.swing.JTextArea showCode;
    // End of variables declaration//GEN-END:variables

    private void choose1MouseClicked() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
